// codesanboxes/vue/tabs/src/App.vue
<template>
  <div>
    <header class="header">
      <h1 class="header-title">
        <a href="/">tabs</a>
      </h1>
      <p class="header-subtitle">
        using
        <a href="https://github.com/algolia/vue-instantsearch">
          Vue InstantSearch
        </a>
      </p>
    </header>

    <div class="container">
      <ais-instant-search :search-client="searchClient" index-name="movies">
        <ais-configure :hits-per-page.camel="1" />

        <ais-search-box
          :placeholder="'Search for movies, actors or directors'"
        />

        <search-tabs default-index="movies-full">
          <!-- Tab 1 -->
          <search-tab :title="'Movies'" :index-id="'movies-full'">
            <ais-index
              index-name="movies"
              index-id="movies-full"
              ref="indexMovies"
            >
              <ais-configure :hits-per-page.camel="8" />
              <div class="search-panel">
                <div class="search-panel__filters">
                  <ais-dynamic-widgets>
                    <ais-refinement-list attribute="actors" />
                    <ais-refinement-list attribute="genres" />
                    <ais-refinement-list attribute="on_sale" />
                    <ais-refinement-list attribute="director" />
                  </ais-dynamic-widgets>
                </div>

                <div class="search-panel__results">
                  <ais-hits>
                    <template v-slot:item="{ item }">
                      <article>
                        <img :src="item.poster" style="max-width: 100%" />
                        <h1>
                          <ais-highlight :hit="item" attribute="title" />
                        </h1>
                      </article>
                    </template>
                  </ais-hits>

                  <div class="pagination">
                    <ais-pagination />
                  </div>
                </div>
              </div>
            </ais-index>
          </search-tab>
          <!-- Tab 2 -->
          <search-tab :title="'Actors'" :index-id="'actors'">
            <ais-index index-name="actors">
              <ais-configure :hits-per-page.camel="8" />
              <div class="search-panel">
                <div class="search-panel__filters"></div>

                <div class="search-panel__results">
                  <ais-hits>
                    <template v-slot:item="{ item }">
                      <article>
                        <img :src="item.picture" style="max-width: 100%" />
                        <h1>
                          <ais-highlight :hit="item" attribute="name" />
                        </h1>
                      </article>
                    </template>
                  </ais-hits>

                  <div class="pagination">
                    <ais-pagination />
                  </div>
                </div>
              </div>
            </ais-index>
          </search-tab>
          <!-- Tab 3 -->
          <search-tab :title="'Directors'" :index-id="'directors'">
            <ais-index index-name="directors">
              <ais-configure :hits-per-page.camel="8" />
              <div class="search-panel">
                <div class="search-panel__filters"></div>

                <div class="search-panel__results">
                  <ais-hits>
                    <template v-slot:item="{ item }">
                      <article>
                        <img :src="item.picture" style="max-width: 100%" />
                        <h1>
                          <ais-highlight :hit="item" attribute="name" />
                        </h1>
                      </article>
                    </template>
                  </ais-hits>

                  <div class="pagination">
                    <ais-pagination />
                  </div>
                </div>
              </div>
            </ais-index>
          </search-tab>
        </search-tabs>
      </ais-instant-search>
    </div>
  </div>
</template>

<script>
import algoliasearch from 'algoliasearch/lite';
import SearchTabs from './components/SearchTabs.vue';
import SearchTab from './components/SearchTab.vue';

export default {
  components: { SearchTabs, SearchTab },
  data() {
    return {
      searchClient: algoliasearch(
        '3EA6KSSDGW',
        '23fef1254e41ec407b1fc80f852e4a40'
      ),
    };
  },
};
</script>

<style>
body,
h1 {
  margin: 0;
  padding: 0;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica,
    Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';
}

h1 {
  font-size: 1rem;
}

em {
  background: cyan;
  font-style: normal;
}

.header {
  display: flex;
  align-items: center;
  min-height: 50px;
  padding: 0.5rem 1rem;
  background-image: linear-gradient(to right, #4dba87, #2f9088);
  color: #fff;
  margin-bottom: 1rem;
}

.header a {
  color: #fff;
  text-decoration: none;
}

.header-title {
  font-size: 1.2rem;
  font-weight: normal;
}

.header-title::after {
  content: ' ▸ ';
  padding: 0 0.5rem;
}

.header-subtitle {
  font-size: 1.2rem;
}

.container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 1rem;
}

.search-panel {
  display: flex;
}

.search-panel__filters {
  flex: 1;
}

.search-panel__results {
  flex: 3;
}

.searchbox {
  margin-bottom: 2rem;
}

.pagination {
  margin: 2rem auto;
  text-align: center;
}
</style>

// codesanboxes/react/tabs/src/App.js
import React from 'react';
import algoliasearch from 'algoliasearch/lite';
import {
  InstantSearch,
  Hits,
  SearchBox,
  RefinementList,
  Pagination,
  Highlight,
  Index,
  Snippet,
  connectStateResults,
  Configure,
} from 'react-instantsearch-dom';
import PropTypes from 'prop-types';
import './App.css';

const searchClient = algoliasearch(
  '3EA6KSSDGW',
  '23fef1254e41ec407b1fc80f852e4a40'
);

class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      currentTab: 'all',
      directorsHitPerPage: 3,
      actorsHitPerPage: 2,
    };
  }

  handleTabClick = event => {
    const newTab = event.target.closest('[data-tab]').dataset.tab;
    this.setState({
      currentTab: newTab,
      directorsHitPerPage: newTab === 'directors' ? 20 : 3,
      actorsHitPerPage: newTab === 'actors' ? 20 : 2,
    });
  };

  render() {
    return (
      <div>
        <header className="header">
          <h1 className="header-title">
            <a href="/">react-instantsearch-app</a>
          </h1>
          <p className="header-subtitle">
            using{' '}
            <a href="https://github.com/algolia/react-instantsearch">
              React InstantSearch
            </a>
          </p>
        </header>

        <div className="container">
          <InstantSearch searchClient={searchClient} indexName="movies">
            <SearchBox
              className="searchbox"
              translations={{
                placeholder: '',
              }}
            />

            <ul className="tabs">
              <li onClick={this.handleTabClick} data-tab="all">
                All (<IndexStats index={['movies', 'actors', 'directors']} />)
              </li>
              <li onClick={this.handleTabClick} data-tab="movies">
                Movies (<IndexStats index="movies" />)
              </li>
              <li onClick={this.handleTabClick} data-tab="products">
                Products (<IndexStats index="products" />)
              </li>
              <li onClick={this.handleTabClick} data-tab="actors">
                Actors (<IndexStats index="actors" />)
              </li>
              <li onClick={this.handleTabClick} data-tab="directors">
                Directors (<IndexStats index="directors" />)
              </li>
            </ul>

            <div
              id="all"
              style={{
                display: this.state.currentTab === 'all' ? null : 'none',
              }}
              className="search-panel"
            >
              <AllHits />
            </div>

            <div
              id="movies"
              style={{
                display: this.state.currentTab === 'movies' ? null : 'none',
              }}
              className="search-panel"
            >
              <Index indexName="movies">
                <div className="search-panel__filters">
                  <RefinementList attribute="genres" />
                </div>

                <div className="search-panel__results">
                  <Hits hitComponent={Movie} />

                  <div className="pagination">
                    <Pagination />
                  </div>
                </div>
              </Index>
            </div>

            <div
              id="products"
              style={{
                display: this.state.currentTab === 'products' ? null : 'none',
              }}
              className="search-panel"
            >
              <Index indexName="demo_products" indexId="products">
                <div className="search-panel__filters">
                  <RefinementList attribute="brand" />
                </div>

                <div className="search-panel__results">
                  <Hits hitComponent={Product} />

                  <div className="pagination">
                    <Pagination />
                  </div>
                </div>
              </Index>
            </div>

            <div
              id="actors"
              style={{
                display: this.state.currentTab === 'actors' ? null : 'none',
              }}
              className="search-panel"
            >
              <Index indexName="actors">
                <Configure hitsPerPage={this.state.actorsHitPerPage} />
                <div className="search-panel__results">
                  <Hits hitComponent={Person} />

                  <div className="pagination">
                    <Pagination />
                  </div>
                </div>
              </Index>
            </div>
            <div
              id="directors"
              style={{
                display: this.state.currentTab === 'directors' ? null : 'none',
              }}
              className="search-panel"
            >
              <Index indexName="directors">
                <Configure hitsPerPage={this.state.directorsHitPerPage} />
                <div className="search-panel__results">
                  <Hits hitComponent={Person} />

                  <div className="pagination">
                    <Pagination />
                  </div>
                </div>
              </Index>
            </div>
          </InstantSearch>
        </div>
      </div>
    );
  }
}

function Movie(props) {
  return (
    <article>
      <img src={props.hit.poster} alt={props.hit.title} width="100%" />
      <h1>
        <Highlight attribute="title" hit={props.hit} />
      </h1>
    </article>
  );
}

Movie.propTypes = {
  hit: PropTypes.object.isRequired,
};

function Product(props) {
  return (
    <article>
      <img src={props.hit.image} alt={props.hit.name} width="100%" />
      <h1>
        <Highlight attribute="name" hit={props.hit} />
      </h1>
      <p>
        <Snippet attribute="description" hit={props.hit} />
      </p>
    </article>
  );
}

Product.propTypes = {
  hit: PropTypes.object.isRequired,
};

function Person(props) {
  return (
    <article>
      <img src={props.hit.picture} alt={props.hit.name} width="100%" />
      <h1>
        <Highlight attribute="name" hit={props.hit} />
      </h1>
      <p>
        <Snippet attribute="biography" hit={props.hit} />
      </p>
    </article>
  );
}

Person.propTypes = {
  hit: PropTypes.object.isRequired,
};

// Widget to display number of hits for each index (or sum of those passed to index prop)
const IndexStatsRender = ({ allSearchResults, index }) => {
  const indexArray = Array.isArray(index) ? index : [index];
  let hits = 0;

  indexArray.forEach(indexID => {
    if (allSearchResults && allSearchResults[indexID]) {
      hits = hits + allSearchResults[indexID].nbHits;
    }
  });

  return <span>{hits}</span>;
};

IndexStatsRender.propTypes = {
  allSearchResults: PropTypes.object,
  index: PropTypes.oneOfType([PropTypes.string, PropTypes.array]).isRequired,
};

const IndexStats = connectStateResults(IndexStatsRender);

// Widget to display All Tab hits
const AllHitsRender = ({ allSearchResults }) => {
  if (!allSearchResults) {
    return <div></div>;
  }

  let directors;
  let actors;

  const movies = allSearchResults.movies ? allSearchResults.movies.hits : [];

  if (
    allSearchResults.directors &&
    allSearchResults.directors.hits.length > 0
  ) {
    directors = (
      <>
        <h2>Directors</h2>
        <ul>
          {allSearchResults.directors.hits.map(hit => (
            <li key={hit.objectID}>{hit.name}</li>
          ))}
        </ul>
      </>
    );
  }

  if (allSearchResults.actors && allSearchResults.actors.hits.length > 0) {
    actors = (
      <>
        <h2>Actors</h2>
        <ul>
          {allSearchResults.actors.hits.map(hit => (
            <li key={hit.objectID}>{hit.name}</li>
          ))}
        </ul>
      </>
    );
  }

  // Mixing Results from different indexes
  const positions = [3, 6, 8, 12, 15];
  const mixedResults = movies.map(movie => ({ hitType: 'Movie', hit: movie }));
  if (allSearchResults.products && allSearchResults.products.hits.length > 0) {
    allSearchResults.products.hits.slice(0, 5).map((hit, index) =>
      mixedResults.splice(positions[index], 0, {
        hitType: 'Product',
        hit,
      })
    );
  }

  return (
    <div className="ais-Hits">
      <ul className="ais-Hits-list">
        <li className="ais-Hits-item" key="diract">
          <article>
            {directors}
            {actors}
          </article>
        </li>
        {mixedResults.map(hit => (
          <li
            className="ais-Hits-item"
            key={`${hit.hitType}-${hit.hit.objectID}`}
          >
            {hit.hitType === 'Movie' ? <Movie hit={hit.hit} /> : ''}
            {hit.hitType === 'Product' ? <Product hit={hit.hit} /> : ''}
          </li>
        ))}
      </ul>
    </div>
  );
};

AllHitsRender.propTypes = {
  allSearchResults: PropTypes.object,
};

const AllHits = connectStateResults(AllHitsRender);

export default App;
